### ISSUE TITLE
Connection crashes after few minutes with medium traffic

### ISSUE THREAD

**Issue by mifritscher** [mobius-software-ltd/java-dtls#1]
Seems to be a problem with key refreshing or something. In GCM-Mode I get "GCM cipher cannot be reused for encryption", in CBC I get "org.bouncycastle.crypto.tls.TlsFatalAlert: bad_record_mac(20)" . I'm using your DtlsClient and DtlsServer .

**Comment by mifritscher** [comment]
Backtrace at Client:

> org.bouncycastle.crypto.tls.TlsFatalAlert: bad_record_mac(20)
> 	at com.mobius.software.iot.dal.crypto.AsyncDtlsRecordLayer.receive(AsyncDtlsRecordLayer.java:243)
> 	at com.mobius.software.iot.dal.crypto.AsyncDtlsClientProtocol.receivePacket(AsyncDtlsClientProtocol.java:125)
> 	at com.mobius.software.iot.dal.crypto.AsyncDtlsClientHandler.decode(AsyncDtlsClientHandler.java:49)
> 	at com.mobius.software.iot.dal.crypto.AsyncDtlsClientHandler.decode(AsyncDtlsClientHandler.java:1)
> 	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
> 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
> 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1408)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
> 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:930)
> 	at io.netty.channel.nio.AbstractNioMessageChannel$NioMessageUnsafe.read(AbstractNioMessageChannel.java:93)
> 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:697)
> 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:632)
> 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:549)
> 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:511)
> 	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:918)
> 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
> 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
> 	at java.base/java.lang.Thread.run(Thread.java:844)


Backtrace at server:

> org.bouncycastle.crypto.tls.TlsFatalAlert: bad_record_mac(20)
> 	at org.bouncycastle.crypto.tls.TlsBlockCipher.decodeCiphertext(Unknown Source)
> 	at com.mobius.software.iot.dal.crypto.AsyncDtlsRecordLayer.receive(AsyncDtlsRecordLayer.java:220)
> 	at com.mobius.software.iot.dal.crypto.AsyncDtlsServerProtocol.receivePacket(AsyncDtlsServerProtocol.java:409)
> 	at com.mobius.software.iot.dal.crypto.AsyncDtlsServerHandler.decode(AsyncDtlsServerHandler.java:76)
> 	at com.mobius.software.iot.dal.crypto.AsyncDtlsServerHandler.decode(AsyncDtlsServerHandler.java:1)
> 	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
> 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
> 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1408)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
> 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:930)
> 	at io.netty.channel.nio.AbstractNioMessageChannel$NioMessageUnsafe.read(AbstractNioMessageChannel.java:93)
> 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:697)
> 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:632)
> 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:549)
> 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:511)
> 	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:918)
> 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
> 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
> 	at java.base/java.lang.Thread.run(Thread.java:844)

Using bc 1.62.

**Comment by yulianoifa-mobius** [comment]
Hello 
In order to identify a problem we would need a last chunk of traffic. Unfortunately the trace does not provides enough information

**Comment by yulianoifa-mobius** [comment]
The error is not reproduceable. New test has been added with 500m/s , overall 1 million of message, The test is passing correctly
The possible hints for the problem are : 
1) Data loss -> any packet that gets lost corrupts the dtls flow
2) Insufficient buffer -> default netty buffer for client is 32KB. If unprocessed packets are overcoming this space the packets will be discarded. To modify it bootstrap.option(ChannelOption.SO_SNDBUF, 65536); and bootstrap.option(ChannelOption.SO_RCVBUF, 65536); may be set for client as it done for server. The buffers may need to be increased further.
3) The cpu and memory usage. In case there is not enough memory / GC is too frequent / not enough CPU, the packets will not get processed on time ,and as result the buffer will get overflowed. 
4) There is theoretical limit of 281,474,976,710,656 packets that may be handled by single channel. After that the sequence would get back to zero and processing will halt. However the number is too big.

BR
Yulian OIfa
